/*--- Before Import ---*/
ALTER TABLE DIFFS DROP FOREIGN KEY DIFFS_IBFK_1;
ALTER TABLE BUGS MODIFY BUG_ID INT NOT NULL;
ALTER TABLE BUGS DROP PRIMARY KEY;


/*--- After Import ---*/
ALTER TABLE BUGS ADD PRIMARY KEY(BUG_ID);
ALTER TABLE DIFFS ADD FOREIGN KEY (`BUG_ID`) REFERENCES `BUGS`(`BUG_ID`) ON DELETE CASCADE ON UPDATE RESTRICT
;