/*--- Before Import ---*/
ALTER TABLE DIFFS DROP FOREIGN KEY DIFFS_IBFK_1;
ALTER TABLE BUGS MODIFY BUG_ID INT NOT NULL;
ALTER TABLE BUGS MODIFY BUGZILLA_PRODUCT VARCHAR(50) NOT NULL;
ALTER TABLE BUGS DROP PRIMARY KEY;


/*--- After Import ---*/
ALTER TABLE BUGS ADD PRIMARY KEY(BUG_ID, BUGZILLA_PRODUCT);
ALTER TABLE DIFFS ADD FOREIGN KEY (`BUG_ID`,`BUGZILLA_PRODUCT`) REFERENCES `BUGS`(`BUG_ID`,`BUGZILLA_PRODUCT`) ON DELETE CASCADE ON UPDATE CASCADE
;

