DROP TABLE IF EXISTS DIFFS;

DROP TABLE IF EXISTS BUGS;

DROP TABLE IF EXISTS RECORD;


CREATE TABLE `BUGS` (
  
`BUG_ID` INTEGER NOT NULL,
  
`BUGZILLA_PRODUCT` VARCHAR(50) NOT NULL,
  
`PRODUCT` VARCHAR(300) NOT NULL,
  
`TITLE` VARCHAR(500) NOT NULL,
  
`IMPORTANCE` VARCHAR(100) NOT NULL,
  
`STATUS` VARCHAR(100) NOT NULL,
  
`DESCRIPTION` MEDIUMTEXT NOT NULL,
  
`PARSE_STATUS` VARCHAR(10) NOT NULL DEFAULT 'PENDING',

PRIMARY KEY (`BUG_ID`, `BUGZILLA_PRODUCT`));





CREATE TABLE `DIFFS` (
  
`BUG_ID` INTEGER NOT NULL,
 
`BUGZILLA_PRODUCT` VARCHAR(50) NOT NULL,
 
`DIFF_ID` INTEGER PRIMARY KEY,
  
`DIFF` MEDIUMTEXT NOT NULL, 
FOREIGN KEY (`BUG_ID`, `BUGZILLA_PRODUCT`) REFERENCES `BUGS`(`BUG_ID`, `BUGZILLA_PRODUCT`) ON DELETE CASCADE ON UPDATE CASCADE);

